CREATE TABLE users (
    UserID UUID PRIMARY KEY,
    PersonName VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Password VARCHAR(50) NOT NULL,
    Gender VARCHAR(50) NOT NULL,
    CONSTRAINT EmailUnique UNIQUE (Email)
);